---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cluster
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        "enable-admission-plugins": "MutatingAdmissionWebhook"
nodes:
  - role: control-plane
