apiVersion: v1
kind: Namespace
metadata:
  name: k8s-image-autoproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-image-autoproxy
  namespace: k8s-image-autoproxy
  labels:
    app: k8s-image-autoproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-image-autoproxy
  template:
    metadata:
      labels:
        app: k8s-image-autoproxy
    spec:
      containers:
        - name: k8s-image-autoproxy
          image: tblaisot/k8s-image-autoproxy:0.0.0
          args:
            - "--proxy"
            - "proxy.io"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: k8s-image-autoproxy-certs
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-image-autoproxy
  namespace: k8s-image-autoproxy
  labels:
    app: k8s-image-autoproxy
spec:
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 443
      targetPort: 8443
  selector:
    app: k8s-image-autoproxy