---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-image-autoproxy

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-image-autoproxy
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-image-autoproxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-image-autoproxy
subjects:
  - kind: ServiceAccount
    name: k8s-image-autoproxy
